
opt_in_rules:
  - force_unwrapping
  - missing_docs
  - empty_collection_literal
  - empty_count
  - implicit_return
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
identifier_name:
  excluded:
    - id
    - url
number_separator:
  minimum_length: 5
custom_rules:
  already_true:
    regex: "== true"
    message: "Don't compare to true, use bool value instead."
    severity: error
  already_false:
    regex: "== false"
    message: "Don't compare to false, use !value instead."
    severity: error